CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    final_winner_player_id BIGINT,
    CONSTRAINT fk_games_winner FOREIGN KEY (final_winner_player_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    round_number INT NOT NULL,
    winner_player_id BIGINT,
    completed_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_rounds_game FOREIGN KEY (game_id) REFERENCES games(id),
    CONSTRAINT fk_rounds_winner FOREIGN KEY (winner_player_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    round_id BIGINT,
    player_id BIGINT NOT NULL,
    round_points INT NOT NULL,
    total_score INT NOT NULL,
    CONSTRAINT fk_scores_game FOREIGN KEY (game_id) REFERENCES games(id),
    CONSTRAINT fk_scores_round FOREIGN KEY (round_id) REFERENCES rounds(id),
    CONSTRAINT fk_scores_player FOREIGN KEY (player_id) REFERENCES players(id)
);
